In [56]:
import pandas as pd;

df_aero = pd.read_csv('../Data/AeroSCOPE_global_aviation_traffic_dataset_16_11.csv',
                       keep_default_na=False, na_values=[''])
df_owid = pd.read_csv('../Data/owid-co2-data.csv')

print(df_aero.shape)
print(df_owid.shape)

print(df_aero.columns)
print(df_owid.columns)

(293838, 26)
(50411, 79)
Index(['Unnamed: 0', 'airline_iata', 'acft_icao', 'acft_class',
       'seymour_proxy', 'source', 'seats', 'n_flights', 'iata_departure',
       'iata_arrival', 'departure_lon', 'departure_lat', 'departure_country',
       'departure_continent', 'arrival_lon', 'arrival_lat', 'arrival_country',
       'arrival_continent', 'seats_no_est_scaling', 'distance_km', 'ask',
       'rpk', 'fuel_burn_seymour', 'fuel_burn', 'co2', 'domestic'],
      dtype='str')
Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='str')

In [57]:
print(df_aero.head())
print(df_owid.head())

   Unnamed: 0 airline_iata acft_icao acft_class seymour_proxy source  seats  \
0           0           5V      PC12         TP          PC12    BTS    4.5
1           1           5V      C208         TP          C208    BTS    4.5
2           2           5V      PC12         TP          PC12    BTS    4.5
3           3           5V      C208         TP          C208    BTS    4.5
4           4           5V      PC12         TP          PC12    BTS    9.0

   n_flights iata_departure iata_arrival  ...  arrival_country  \
0        0.5            05A          AET  ...               US
1        0.5            05A          AKP  ...               US
2        0.5            05A          AKP  ...               US
3        0.5            05A          ARC  ...               US
4        1.0            05A          CXF  ...               US

   arrival_continent seats_no_est_scaling distance_km          ask  \
0                 NA                  4.5  223.942934  1007.743204
1                 NA                  4.5  162.423657   730.906457
2                 NA                  4.5  162.423657   730.906457
3                 NA                  4.5  125.368872   564.159925
4                 NA                  9.0   93.591691   842.325219

          rpk fuel_burn_seymour  fuel_burn         co2  domestic
0  830.380400        124.087173  62.043586  196.057733         1
1  602.266920        101.150619  50.575310  159.817978         1
2  602.266920        104.747398  52.373699  165.500889         1
3  464.867779         86.356979  43.178490  136.444027         1
4  694.075981         83.360861  83.360861  263.420321         1

[5 rows x 26 columns]
       country  year iso_code  population  gdp  cement_co2  \
0  Afghanistan  1750      AFG   2802560.0  NaN         0.0
1  Afghanistan  1751      AFG         NaN  NaN         0.0
2  Afghanistan  1752      AFG         NaN  NaN         0.0
3  Afghanistan  1753      AFG         NaN  NaN         0.0
4  Afghanistan  1754      AFG         NaN  NaN         0.0

   cement_co2_per_capita  co2  co2_growth_abs  co2_growth_prct  ...  \
0                    0.0  NaN             NaN              NaN  ...
1                    NaN  NaN             NaN              NaN  ...
2                    NaN  NaN             NaN              NaN  ...
3                    NaN  NaN             NaN              NaN  ...
4                    NaN  NaN             NaN              NaN  ...

   share_global_other_co2  share_of_temperature_change_from_ghg  \
0                     NaN                                   NaN
1                     NaN                                   NaN
2                     NaN                                   NaN
3                     NaN                                   NaN
4                     NaN                                   NaN

   temperature_change_from_ch4  temperature_change_from_co2  \
0                          NaN                          NaN
1                          NaN                          NaN
2                          NaN                          NaN
3                          NaN                          NaN
4                          NaN                          NaN

   temperature_change_from_ghg  temperature_change_from_n2o  total_ghg  \
0                          NaN                          NaN        NaN
1                          NaN                          NaN        NaN
2                          NaN                          NaN        NaN
3                          NaN                          NaN        NaN
4                          NaN                          NaN        NaN

   total_ghg_excluding_lucf  trade_co2  trade_co2_share
0                       NaN        NaN              NaN
1                       NaN        NaN              NaN
2                       NaN        NaN              NaN
3                       NaN        NaN              NaN
4                       NaN        NaN              NaN

[5 rows x 79 columns]

In [58]:
# recherche du nom de l'A320ceo et A320neo
df_aero[df_aero['acft_icao'].str.contains('A320|A20N')]['acft_icao'].unique()

<StringArray>
['A320', 'A20N']
Length: 2, dtype: str

In [59]:
df_a320 = df_aero[df_aero['acft_icao'].str.contains('A320|A20N')]

df_a320.shape

(37046, 26)

In [60]:
df_a320.isnull().sum()

Unnamed: 0              0
airline_iata            0
acft_icao               0
acft_class              0
seymour_proxy           0
source                  0
seats                   0
n_flights               0
iata_departure          0
iata_arrival            0
departure_lon           0
departure_lat           0
departure_country       0
departure_continent     0
arrival_lon             0
arrival_lat             0
arrival_country         0
arrival_continent       0
seats_no_est_scaling    0
distance_km             0
ask                     0
rpk                     0
fuel_burn_seymour       0
fuel_burn               0
co2                     0
domestic                0
dtype: int64

In [61]:
df_a320.dtypes

Unnamed: 0                int64
airline_iata                str
acft_icao                   str
acft_class                  str
seymour_proxy               str
source                      str
seats                   float64
n_flights               float64
iata_departure              str
iata_arrival                str
departure_lon           float64
departure_lat           float64
departure_country           str
departure_continent         str
arrival_lon             float64
arrival_lat             float64
arrival_country             str
arrival_continent           str
seats_no_est_scaling    float64
distance_km             float64
ask                     float64
rpk                     float64
fuel_burn_seymour       float64
fuel_burn               float64
co2                     float64
domestic                  int64
dtype: object

In [62]:
df_a320[['co2', 'distance_km', 'seats', 'fuel_burn']].describe()

                co2   distance_km          seats     fuel_burn
count  3.704600e+04  37046.000000   37046.000000  3.704600e+04
mean   1.319908e+06   1534.733591   14241.927628  4.176923e+05
std    2.748222e+06    980.184455   31984.937998  8.696905e+05
min    0.000000e+00      0.000000       0.000000  0.000000e+00
25%    3.310374e+04    804.580259     498.187500  1.047587e+04
50%    3.062777e+05   1409.747206    3238.218750  9.692331e+04
75%    1.329003e+06   2109.709557   13700.156250  4.205704e+05
max    5.582050e+07  15872.770078  919986.250000  1.766471e+07

In [63]:
df_a320 = df_a320[(df_a320['co2'] > 0) & (df_a320['distance_km'] > 0)]
df_a320.shape

(36496, 26)

In [71]:
df_a320['type_appareil'] = df_a320['acft_icao'].map({'A320': 'ceo', 'A20N': 'neo'})

df_a320['type_appareil'].value_counts()

type_appareil
ceo    30778
neo     5718
Name: count, dtype: int64

In [65]:
part_a320 = df_a320.shape[0] / df_aero.shape[0] * 100
print(f" {part_a320:.1f}")

 12.4

## Insight #1
Les A320 (ceo + neo) représentent **12.4% des routes mondiales** dans le dataset AeroSCOPE.

In [66]:
df_a320['acft_icao'].value_counts()

acft_icao
A320    30778
A20N     5718
Name: count, dtype: int64

In [67]:
counts = df_a320['acft_icao'].value_counts()
part_neo = counts['A20N'] / counts.sum() * 100
print(f"Le A320neo représente {part_neo:.1f}% de la flotte A320")

Le A320neo représente 15.7% de la flotte A320

##  Insight #2
Sur les 36 496 routes opérées par des A320, seulement **15.7% sont en A320neo**.
84.3% de la flotte A320 est encore en ceo ce qui représente un **énorme potentiel de réduction CO₂** si la transition s'accélère.

In [73]:
df_a320_clean = df_a320[['type_appareil','airline_iata','iata_departure','iata_arrival','departure_country','arrival_country','departure_continent','arrival_continent','distance_km','co2','seats','n_flights']]

In [76]:
df_a320_clean.shape
df_a320_clean.head()

,type_appareil,airline_iata,iata_departure,iata_arrival,departure_country,arrival_country,departure_continent,arrival_continent,distance_km,co2,seats,n_flights
145,ceo,G4,ABE,AVL,US,US,NA,NA,850.005218,10955.546533,186.0,1.0
156,ceo,G4,ABE,BNA,US,US,NA,NA,1101.575025,863672.536078,11799.0,66.0
189,ceo,UA,ABE,DEN,US,US,NA,NA,2476.779362,12825.542159,75.0,0.5
192,ceo,DL,ABE,DTW,US,US,NA,NA,683.246599,4786.014829,78.5,0.5
202,ceo,DL,ABE,EWR,US,US,NA,NA,107.819675,2486.742458,78.5,0.5

In [77]:
df_a320_clean.to_csv('../Data/a320_clean.csv', index=False)